name: C++ Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Clang
        run: sudo apt-get update && sudo apt-get install -y git clang

      - name: Test C++ files
        run: |
          for commit in $(git rev-list ${{ github.base_ref }}..${{ github.head_ref }}); do
            problem=$(git diff --name-only --diff-filter=AM $commit^1...$commit | grep '.cpp' | sed 's/.cpp//g' | xargs)
            echo $(git diff --name-only --diff-filter=AM HEAD^1...HEAD)
            if [[ -n "$problem" ]]; then
              clang++ -std=c++20 -fsanitize=address -o "$problem" "$problem".cpp
              result=$(python3 test.py $problem)
              echo "$result"
              if [[ $result == "FAIL" ]]; then
                echo "Tests failed"
                exit 1
              else
                echo "All tests passed"
              fi
            else
              # Success github actions early
              echo "No C++ file modified"
              exit 0
            fi
          done