name: C++ Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Clang
        run: |
          if ! [ -x "$(command -v sudo)" ]; then
            apt-get update
            apt-get install -y sudo
          fi
          sudo apt-get update && sudo apt-get install -y git clang

      - name: Test C++ files
        run: |
          for commit in $(git rev-list ${{ github.base_ref }}..${{ github.head_ref }}); do
            for problem in $(git diff --name-only --diff-filter=AM $commit^1...$commit | grep '.cpp' | xargs); do
              bin_file=bin/`echo $problem | sed 's/.cpp//g'`
              clang++ -std=c++20 -fsanitize=address -o $bin_file $problem
              python3 test.py $problem
              if [[ $? -ne 0 ]]; then
                exit 1
              fi
            done
          done