name: C++ Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          if ! [ -x "$(command -v sudo)" ]; then
            apt-get update
            apt-get install -y sudo
          fi
          sudo apt-get update && sudo apt-get install -y git clang python3-pip
          pip3 install -r requirements.txt

      - name: Test C++ files
        run: |
          bash test.sh